python3 answer.py ../ask/data/set1a1.txt set1a1.txt > data/answerset1a1.txt
python3 answer.py ../ask/data/set1a2.txt set1a2.txt > data/answerset1a2.txt
python3 answer.py ../ask/data/set1a3.txt set1a3.txt > data/answerset1a3.txt
python3 answer.py ../ask/data/set1a4.txt set1a4.txt > data/answerset1a4.txt
python3 answer.py ../ask/data/set1a5.txt set1a5.txt > data/answerset1a5.txt
python3 answer.py ../ask/data/set1a6.txt set1a6.txt > data/answerset1a6.txt
python3 answer.py ../ask/data/set1a7.txt set1a7.txt > data/answerset1a7.txt
python3 answer.py ../ask/data/set1a8.txt set1a8.txt > data/answerset1a8.txt
python3 answer.py ../ask/data/set1a9.txt set1a9.txt > data/answerset1a9.txt
python3 answer.py ../ask/data/set1a10.txt set1a10.txt > data/answerset1a10.txt
python3 answer.py ../ask/data/set2a1.txt set2a1.txt > data/answerset2a1.txt
python3 answer.py ../ask/data/set2a2.txt set2a2.txt > data/answerset2a2.txt
python3 answer.py ../ask/data/set2a3.txt set2a3.txt > data/answerset2a3.txt
python3 answer.py ../ask/data/set2a4.txt set2a4.txt > data/answerset2a4.txt
python3 answer.py ../ask/data/set2a5.txt set2a5.txt > data/answerset2a5.txt
python3 answer.py ../ask/data/set2a6.txt set2a6.txt > data/answerset2a6.txt
python3 answer.py ../ask/data/set2a7.txt set2a7.txt > data/answerset2a7.txt
python3 answer.py ../ask/data/set2a8.txt set2a8.txt > data/answerset2a8.txt
python3 answer.py ../ask/data/set2a9.txt set2a9.txt > data/answerset2a9.txt
python3 answer.py ../ask/data/set2a10.txt set2a10.txt > data/answerset2a10.txt
python3 answer.py ../ask/data/set3a1.txt set3a1.txt > data/answerset3a1.txt
python3 answer.py ../ask/data/set3a2.txt set3a2.txt > data/answerset3a2.txt
python3 answer.py ../ask/data/set3a3.txt set3a3.txt > data/answerset3a3.txt
python3 answer.py ../ask/data/set3a4.txt set3a4.txt > data/answerset3a4.txt
python3 answer.py ../ask/data/set3a5.txt set3a5.txt > data/answerset3a5.txt
python3 answer.py ../ask/data/set3a6.txt set3a6.txt > data/answerset3a6.txt
python3 answer.py ../ask/data/set3a7.txt set3a7.txt > data/answerset3a7.txt
python3 answer.py ../ask/data/set3a8.txt set3a8.txt > data/answerset3a8.txt
python3 answer.py ../ask/data/set3a9.txt set3a9.txt > data/answerset3a9.txt
python3 answer.py ../ask/data/set3a10.txt set3a10.txt > data/answerset3a10.txt
python3 answer.py ../ask/data/set4a1.txt set4a1.txt > data/answerset4a1.txt
python3 answer.py ../ask/data/set4a2.txt set4a2.txt > data/answerset4a2.txt
python3 answer.py ../ask/data/set4a3.txt set4a3.txt > data/answerset4a3.txt
python3 answer.py ../ask/data/set4a4.txt set4a4.txt > data/answerset4a4.txt
python3 answer.py ../ask/data/set4a5.txt set4a5.txt > data/answerset4a5.txt
python3 answer.py ../ask/data/set4a6.txt set4a6.txt > data/answerset4a6.txt
python3 answer.py ../ask/data/set4a7.txt set4a7.txt > data/answerset4a7.txt
python3 answer.py ../ask/data/set4a8.txt set4a8.txt > data/answerset4a8.txt
python3 answer.py ../ask/data/set4a9.txt set4a9.txt > data/answerset4a9.txt
python3 answer.py ../ask/data/set4a10.txt set4a10.txt > data/answerset4a10.txt
python3 answer.py ../ask/data/set5a1.txt set5a1.txt > data/answerset5a1.txt
python3 answer.py ../ask/data/set5a2.txt set5a2.txt > data/answerset5a2.txt
python3 answer.py ../ask/data/set5a3.txt set5a3.txt > data/answerset5a3.txt
python3 answer.py ../ask/data/set5a4.txt set5a4.txt > data/answerset5a4.txt
python3 answer.py ../ask/data/set5a5.txt set5a5.txt > data/answerset5a5.txt
python3 answer.py ../ask/data/set5a6.txt set5a6.txt > data/answerset5a6.txt
python3 answer.py ../ask/data/set5a7.txt set5a7.txt > data/answerset5a7.txt
python3 answer.py ../ask/data/set5a8.txt set5a8.txt > data/answerset5a8.txt
python3 answer.py ../ask/data/set5a9.txt set5a9.txt > data/answerset5a9.txt
python3 answer.py ../ask/data/set5a10.txt set5a10.txt > data/answerset5a10.txt
