#!/usr/bin/env python3

import sys
from question_type import QuestionType
from top_k_sentences import ArticleQuestions
from wh import WHQ
from yes_no import yes_no_answer

if __name__ == '__main__':
    print('start')
    try:
        article_file = sys.argv[1]
        questions_file = sys.argv[2]
    except:
        print('usage: python ./answer.py <path to article> <path to questions>')

    # Process article and questions
    article_questions = ArticleQuestions(article_file, questions_file, 1)
    print('1')
    # Narrow down search range
    questions_top_sentences = article_questions.question_article_similarity()

    # Figure out the type of each question
    qt = QuestionType(article_questions.questions)
    print('2')
    answer = {}
    print(qt.question_type)
    for question, qtype in qt.questions_type_dict.items():
        print(question,qtype)
        if qtype == 'YESNO':
            answer[question] = yes_no_answer(questions_top_sentences[question], question)
        else:
            whq = WHQ(question, qtype, questions_top_sentences[question])
            answer[question] = whq.find_answers()
        print(answer[question])
    print('3')
    for i, (q, a) in enumerate(answer.items()):
        print(q)
        a = "A{} {}\n".format(i+1, a)
        sys.stdout.buffer.write(a.encode('utf8'))