python3 ask.py ../data/Development_data/set1/a1.txt 10
python3 ask.py ../data/Development_data/set1/a2.txt 10
python3 ask.py ../data/Development_data/set1/a3.txt 10
python3 ask.py ../data/Development_data/set1/a4.txt 10
python3 ask.py ../data/Development_data/set1/a5.txt 10
python3 ask.py ../data/Development_data/set1/a6.txt 10
python3 ask.py ../data/Development_data/set1/a7.txt 10
python3 ask.py ../data/Development_data/set1/a8.txt 10
python3 ask.py ../data/Development_data/set1/a9.txt 10
python3 ask.py ../data/Development_data/set1/a10.txt 10
python3 ask.py ../data/Development_data/set2/a1.txt 10
python3 ask.py ../data/Development_data/set2/a2.txt 10
python3 ask.py ../data/Development_data/set2/a3.txt 10
python3 ask.py ../data/Development_data/set2/a4.txt 10
python3 ask.py ../data/Development_data/set2/a5.txt 10
python3 ask.py ../data/Development_data/set2/a6.txt 10
python3 ask.py ../data/Development_data/set2/a7.txt 10
python3 ask.py ../data/Development_data/set2/a8.txt 10
python3 ask.py ../data/Development_data/set2/a9.txt 10
python3 ask.py ../data/Development_data/set2/a10.txt 10
python3 ask.py ../data/Development_data/set3/a1.txt 10
python3 ask.py ../data/Development_data/set3/a2.txt 10
python3 ask.py ../data/Development_data/set3/a3.txt 10
python3 ask.py ../data/Development_data/set3/a4.txt 10
python3 ask.py ../data/Development_data/set3/a5.txt 10
python3 ask.py ../data/Development_data/set3/a6.txt 10
python3 ask.py ../data/Development_data/set3/a7.txt 10
python3 ask.py ../data/Development_data/set3/a8.txt 10
python3 ask.py ../data/Development_data/set3/a9.txt 10
python3 ask.py ../data/Development_data/set3/a10.txt 10
python3 ask.py ../data/Development_data/set4/a1.txt 10
python3 ask.py ../data/Development_data/set4/a2.txt 10
python3 ask.py ../data/Development_data/set4/a3.txt 10
python3 ask.py ../data/Development_data/set4/a4.txt 10
python3 ask.py ../data/Development_data/set4/a5.txt 10
python3 ask.py ../data/Development_data/set4/a6.txt 10
python3 ask.py ../data/Development_data/set4/a7.txt 10
python3 ask.py ../data/Development_data/set4/a8.txt 10
python3 ask.py ../data/Development_data/set4/a9.txt 10
python3 ask.py ../data/Development_data/set4/a10.txt 10
python3 ask.py ../data/Development_data/set5/a1.txt 10
python3 ask.py ../data/Development_data/set5/a2.txt 10
python3 ask.py ../data/Development_data/set5/a3.txt 10
python3 ask.py ../data/Development_data/set5/a4.txt 10
python3 ask.py ../data/Development_data/set5/a5.txt 10
python3 ask.py ../data/Development_data/set5/a6.txt 10
python3 ask.py ../data/Development_data/set5/a7.txt 10
python3 ask.py ../data/Development_data/set5/a8.txt 10
python3 ask.py ../data/Development_data/set5/a9.txt 10
python3 ask.py ../data/Development_data/set5/a10.txt 10
python3 ask.py ../data/noun_counting_data/a5.txt 10
python3 ask.py ../data/noun_counting_data/a5.txt 10
python3 ask.py ../data/noun_counting_data/a5.txt 10
python3 ask.py ../data/noun_counting_data/a5.txt 10
python3 ask.py ../data/noun_counting_data/a5.txt 10
python3 ask.py ../data/noun_counting_data/a5.txt 10
python3 ask.py ../data/noun_counting_data/a5.txt 10
python3 ask.py ../data/noun_counting_data/a5.txt 10
python3 ask.py ../data/noun_counting_data/a5.txt 10
python3 ask.py ../data/noun_counting_data/a5.txt 10
